### PR TITLE
moving artifact_correction function to be the first correction applied

### PR DESCRIPTION
**Pull request by Kernl67**
the L1_calibrate outputs are changed : image_lsb_no_art (after artifact correction) is added and image_calib_no_art is removed the order of the errorflags are not changed

### CODE REVIEW

**Comment by skymandr** [comment]
Is this to be considered a bug fix, so that this should be included in the current version when I re-run it?

**Comment by Kernl67** [comment]
Yes this should be added to the current version rerun, the artifact correction is currently not applied the way it was supposed to in the L1b v0.5 version

**Comment by lindamegner** [comment]
Don't merge this until I have talked to Louis.I think we may want the correction where it was. Sorry Louis, I meant to discuss this with you yesterday but things got in the way.

**Review by OleMartinChristensen — CHANGES_REQUESTED** [review]
this seems to not be correctly implemented. Do not merge

**Review by OleMartinChristensen — APPROVED** [review]
Approved but new issue opened on this

**Comment by lindamegner** [comment]
This is a bit confusing, but we want the artifact correction in the last stage of the calibration.  If I understand correctly this is a intermediate version where the error flags work.  But then issue https://github.com/innosat-mats/MATS-L1-processing/issues/170 is opened to move the artifact correction to the end of the calibration.  Have I understood it correctly?

**Comment by OleMartinChristensen** [comment]
Yes, on the long term we want this but with the current tables and implementation we need to have artifact as the first, thus thus was merged in and used in the v0.5 of the l1b processing (and thus this issue is closed). 

Then for l1bv0.6  we might move it (thus the new issue was opened)

**Pull request merged**
