### PR TITLE
Added medina filter of 3 horizontal pixels when constructing flatfiel…

### PR DESCRIPTION
**Pull request by lindamegner**
…ds from the lab measurements.

### CODE REVIEW

**Comment by lindamegner** [comment]
Median. Not Medina filter :)

**Review by OleMartinChristensen — COMMENTED** [review]
You also seem to add the star database? why?

**Comment by skymandr** [comment]
> You also seem to add the star database? why?

To me it looks like it's been added to `.gitignore` in order to avoid checking it in by mistake (note also, that more up to date versions of the Ephemeris data are available... ;) ).

**Review by OleMartinChristensen — APPROVED** [review]
looks good

**Pull request merged**
